### ISSUE TITLE
Prohibitive runtime for isoformSwitchTestDEXSeq due to DEXSeq::estimateDispersions step

### ISSUE THREAD

**Issue by stperiocuhl** [kvittingseerup/IsoformSwitchAnalyzeR#121]
Hello,

We are trying to analyze isoform switches between two groups (n ≈ 500 samples total), for ≈5,000 isoforms from ≈2,000 genes.  However, we have encountered some difficulties in running the `isoformSwitchTestDEXSeq` function: when applied to our data, the estimated runtime is on the order of several years (by contrast, we have successfully run the same analysis on a much smaller dataset of n = 12 samples, and it completes in <10 minutes).  After some debugging, we observed that the function is stalling at the `DEXSeq::estimateDispersions` step, where it seems to get "stuck".  We are aware that dispersion estimation for exons is expected to take longer than for genes (as if using DESeq2), but as the function has not progressed past this step after running continuously for a full week, we are concerned that we may be overlooking something.

Is it possible to analyze a dataset of this size using IsoformSwitchAnalyzeR in a reasonable amount of time?  If so, would you be able to recommend any methods for speeding up the runtime of the `isoformSwitchTestDEXSeq` function (particularly the `DEXSeq::estimateDispersions` step)?  We have considered analyzing the data in smaller batches as a last resort, but are hesitant to do so given the impacts it may have on accuracy.

Any insights you can offer would be greatly appreciated.  Thank you for your time!

**Comment by kvittingseerup** [comment]
Hi

This is a known problem caused by DEXSeq having a runtime that exponentially depends on the number of samples. There is unfortunately currently not a good way of doing this directly within IsoformSwitchAnalyzeR.

What you can do is:

1. to take the expression matrix and test the same isoforms as are in the `<switch_list>$isoformFeatures` part of the object (after running preFilter).
2. This matrix can be analyzed by a different DTU tool. I would suggest you take a look at this [article](https://f1000research.com/articles/10-374) to find a suitable one.
3. Once you have the FDR corrected p-values you can overwrite the `gene_switch_q_value` and `isoform_switch_q_value` columns in the `<switch_list>$isoformFeatures`.
4. Lastly simply run preFilter() telling it to filter on significance.

Hope this helps

Cheers
Kristoffer
