### ISSUE TITLE
How do I get alternative splice results for each sample

### ISSUE THREAD

**Issue by 1156054203** [kvittingseerup/IsoformSwitchAnalyzeR#123]
I use your software for data analysis and it's very handy. I have a question about how do I get the alternative splice results for each sample from IsoformSwitchAnalyzeR object. Looking forward to your reply.

**Comment by kvittingseerup** [comment]
The short answer is that you cannot - and I'm not even sure why you would do it.

The long answer is that alternative splicing truly unique to one sample is very(!) rare. This almost only occurs when you modify the genome with CRISPR or similar - else there is always (very) low level of the splice variant in one condition and high level in another condition. This also means that just counting unique splice features from different conditions will result in almost no difference.

Furthermore, since alternative splicing is very abundant the non-chaining splice sites will drown out the interesting once - those actually changing between conditions.

This is why IsoformSwitchAnalyzeR focuses on identifying and analyzing the isoforms actually changing between conditions.

I hope this makes sense - else please don't hesitate to let me know
