### ISSUE TITLE
aSwitchList error

### ISSUE THREAD

**Issue by KrRi4** [kvittingseerup/IsoformSwitchAnalyzeR#179]
Hello!

I am attempting to run analysis with this tool but running into an issue when creating the aSwitchList.   

I'm using salmon output with gencode gtf and when I run the command:

aSwitchList <- importRdata(
  isoformCountMatrix   = salmonQuant$counts,
  isoformRepExpression = salmonQuant$abundance,
  designMatrix         = myDesign,
  isoformExonAnnoation = "/Users/xx/GenomeFiles/gencode.v40.primary_assembly.annotation.gtf",
  #isoformNtFasta       = "/Users/xx/GenomeFiles/xx.fa",
  fixStringTieAnnotationProblem = F,
  showProgress = F
)

it stops with the following error:

Step 1 of 7: Checking data...
Step 2 of 7: Obtaining annotation...
    importing GTF (this may take a while)...
Error in `dplyr::full_join()`:
! `...` must be empty.
✖ Problematic argument:
• all = TRUE

some info on the env:
sessionInfo()
R version 4.1.3 (2022-03-10)

dplyr_1.1.0 
tidyverse_2.0.0 
 IsoformSwitchAnalyzeR_1.16.0

Any idea on what this could be? 

Thanks!

**Comment by kvittingseerup** [comment]
You just need to upgrade to the newest version from github :-)

And for future reference please don't cross-post problems. Also, this issue has already been raised several times so remember to search for the problem before making a new issue.

**Comment by KrRi4** [comment]
Hi Dr. Vittin-Seerup,

I'm making good progress with analysis using IsoformSwitchAnalyzer.

I had some data that was confounded by batch so recently used combat-seq to
adjust the raw count estimates from Salmon.  I planned on importing this
into the ImportRdata function.  However,  I'm getting the following error
when I run the command below:

aSwitchList <- importRdata(

  isoformCountMatrix   = as.data.frame(salmonQuant$counts),

#  isoformRepExpression = salmonQuant$abundance,

  designMatrix         = myDesignNoB,

  isoformExonAnnoation = "final.gtf",

  isoformNtFasta       = "gencode.fa",

  fixStringTieAnnotationProblem = F,

  showProgress = T

)

# the function fails below:

Step 1 of 10: Checking data...

Step 2 of 10: Obtaining annotation...

    importing GTF (this may take a while)...

    64628 ( 14.72%) isoforms were removed since they were not expressed in
any samples.

Error in importRdata(isoformCountMatrix = salmonQuant$counts,  :

  No sequences in the fasta files had IDs matching the expression data.
This problem might be solvable using some of the 'ignoreAfterBar',
'ignoreAfterSpace' or 'ignoreAfterPeriod' arguments.

     3 Examples from expression matrix are :

     3 Examples of sequence annotation are : ENST00000599628.5,
PB.15388.44, PB.1893.1



It looks like it's expecting an   isoformRepExpression file.  I thought
this was optional and was expecting the function to estimate abundance
using the estimated adjusted counts.   Is this the expected behavior?

When I add an abundance file( salmonQuant$abundance) to this it runs
without issue, but it appears to be using the abundances derived from the
unadjusted counts.   Is there a way to skip defining  isoformRepExpression
dataset and having isoformswitchanalyzer estimate abundance?

Thanks again!
Kris

**Comment by kvittingseerup** [comment]
This is rater a problem with the tx ids in the replicate count matrix needing to match what are in the gtf. How are your tx ids added to the count matrix?
________________________________
Fra: KR ***@***.***>
Sendt: Wednesday, June 14, 2023 11:13:04 PM
Til: kvittingseerup/IsoformSwitchAnalyzeR ***@***.***>
Cc: Kristoffer Vitting-Seerup ***@***.***>; State change ***@***.***>
Emne: Re: [kvittingseerup/IsoformSwitchAnalyzeR] aSwitchList error (Issue #179)


Hi Dr. Vittin-Seerup,

I'm making good progress with analysis using IsoformSwitchAnalyzer.

I had some data that was confounded by batch so recently used combat-seq to
adjust the raw count estimates from Salmon. I planned on importing this
into the ImportRdata function. However, I'm getting the following error
when I run the command below:

aSwitchList <- importRdata(

isoformCountMatrix = as.data.frame(salmonQuant$counts),

# isoformRepExpression = salmonQuant$abundance,

designMatrix = myDesignNoB,

isoformExonAnnoation = "final.gtf",

isoformNtFasta = "gencode.fa",

fixStringTieAnnotationProblem = F,

showProgress = T

)

# the function fails below:

Step 1 of 10: Checking data...

Step 2 of 10: Obtaining annotation...

importing GTF (this may take a while)...

64628 ( 14.72%) isoforms were removed since they were not expressed in
any samples.

Error in importRdata(isoformCountMatrix = salmonQuant$counts, :

No sequences in the fasta files had IDs matching the expression data.
This problem might be solvable using some of the 'ignoreAfterBar',
'ignoreAfterSpace' or 'ignoreAfterPeriod' arguments.

3 Examples from expression matrix are :

3 Examples of sequence annotation are : ENST00000599628.5,
PB.15388.44, PB.1893.1



It looks like it's expecting an isoformRepExpression file. I thought
this was optional and was expecting the function to estimate abundance
using the estimated adjusted counts. Is this the expected behavior?

When I add an abundance file( salmonQuant$abundance) to this it runs
without issue, but it appears to be using the abundances derived from the
unadjusted counts. Is there a way to skip defining isoformRepExpression
dataset and having isoformswitchanalyzer estimate abundance?

Thanks again!
Kris

**Comment by kvittingseerup** [comment]
Good to hear. Unfortunatly the `switchPlot()` is a composite plot, so there is no easy way to change the plot once it have been created. The solution is use the `localTheme` option in the `switchPlot()` function. It default to `theme_bw(base_size = 8)` but if you incease this and all text sizes should be increased.

Best of luck with your analysis :-)
