### ISSUE TITLE
extractSwitchSummary more switches than isoforms?

### ISSUE THREAD

**Issue by gbouras13** [kvittingseerup/IsoformSwitchAnalyzeR#186]
Hi @kvittingseerup,

I am undertaking a pretty straightforward analysis - 3 treated (CRS) samples vs 4 control samples using Nanopore cDNA data.

Using version 2.1.12. 

I essentially followed the vignette with my data once I read it in and am just wrapping up my analysis, but I am a bit confused about the output of ExtractSwitchSummary for some summary stats:

I got this:

```
ExtractSwitchSummary(exampleSwitchListAnalyzed, alpha = 0.1)
   Comparison nrIsoforms nrSwitches nrGenes
 CTRL vs CRS         92        110      80
```

I am a bit confused - how is it possible to get more Switches than Isoforms?

I can see how nrIsoforms can be < 2*nrSwitches (if one side of the switch has a non-significant isoform - seems to be pretty common in my dataset), but not how nrSwitches can be larger than nrIsoforms. 

Apologies if I have misunderstood what significant Switches and Isoforms are as well!

George

**Comment by kvittingseerup** [comment]
Thanks for reaching out 🙂

You can have `switches > isoforms` because switches are per definition pairs of isoforms. This also means that if you have a gene with 3 isoforms you can have 3 pairs (a vs b, a vs c and b vs c), if you have 4 isoforms you can make 6 possible combinations and so forth.

Based on your last comment you might want to look at the `onlySigIsoforms` argument in the test you are using 🙂
