### ISSUE TITLE
Questions about AS type

### ISSUE THREAD

**Issue by moomin1347** [kvittingseerup/IsoformSwitchAnalyzeR#192]
Hello,
Thank you for developing this great tool! 
When I use analyzeAlternativeSplicing(), I have three questions:
1. Dose ATTS(Alternative Transcription Termination Site) means alternative splicing of the last exon?

2. The software identifies AS events by comparing initial and mature mRNA, but other AS analysis software compares different mature transcripts. What's the difference? Can you briefly tell me about spliceR's strategy for identifying AS events?

3. Why it is not OK to get the AS type of a sample separately? I see a related question, but I still don't understand it.

Thanks and best wishes,
Liu

**Comment by kvittingseerup** [comment]
Thanks for the kind words 😞

I've tried to answer the questions below:

1. It "just" means that the termination site is different. Could both be alternative splicing of the last exon or because two different exons are the last one in each transcript. If you care about this distinction, you can use `analyzeSwitchConsequences()` to investigate.
2. If you "only" compare two transcripts, you might misclassify an event. The classical example would be intron retention found in both the transcripts you are interested in. If you don't take all of the genomic information (all transcripts) into account using, e.g., a hypothetical pre-mRNA, you would not know there was an intron retention when you compared those two transcripts.
3. If you want to compare AS between samples, you need to ensure that all events were quantified in both samples - else you cannot compare them (aka you would be comparing apples and oranges). But if you are using IsoformSwitchAnalyzeR you don't have that problem.

I hope that answers your questions - else let me know 🙂
