### ISSUE TITLE
pfam webserver output files incompatibility

### ISSUE THREAD

**Issue by Blondeau-Bidet** [kvittingseerup/IsoformSwitchAnalyzeR#227]
Hello,

I'm encountering a problem when I want to incorporate the results of the Pfam analysis into the switchAnalyzeRlist object. I performed the analysis via the web server (at this address: https://www.ebi.ac.uk/interpro/search/sequence/). 

An example of the analysis results is attached to this message. I have 23 such files, which I have concatenated into 1 file.
[pfam_1_23.txt](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/files/14298322/pfam_1_23.txt)

Here's the command line I use: 
aSwitchList_filter_Analyzed <- analyzePFAM(
  switchAnalyzeRlist = aSwitchList_filter_Analyzed,
  pathToPFAMresultFile = "path/pfam_result.txt",
  showProgress = FALSE)

And here's the R error message: 
Error in h(simpleError(msg, call)): 
  error in ï¿½valuation of argument 'x' when selecting a method for function 'unique' : error in ï¿½valuation of argument 'args' when selecting a method for function 'do. call': error in evaluation of argument 'x' when selecting a method for the 'unique' function: error in evaluation of argument 'x' when selecting a method for the 'which' function: undefined columns selected.
Also: Advisory message:
In scan(file = file, what = what, sep = sep, quote = quote, dec = dec, :
  End of file (EOF) in a string between quotation marks

I also tried an external analysis from this address (it corresponds to the link indicated in the package documentation ) : https://www.ebi.ac.uk/Tools/hmmer/search/hmmscan. But that doesn't work either. I get the same error message. 

Here an example of the output file : 
[test_2.txt](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/files/14298530/test_2.txt)

Is there a solution to this problem?

Eva

**Comment by chunxubioinfor** [comment]
Hi Eva, I think this error is due to the incompatibility of the output file. I checked your `test_2.txt` file, and I assume you just pasted one sequence and downloaded the .txt output file. This output file looks strange and different from the normal one (I attached an example [pfam_results.txt](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/files/14336723/pfam_results.txt) of standard Pfam output), and I guess if you upload the sequences file, then you can get the right output compatible with the analyzePFAM function. 

Btw I tried to upload my files to this web server, and it's so slow. So I recommend you run locally if possible. 😊

**Comment by Blondeau-Bidet** [comment]
Hi Han,

Thank you for your reply.
You're right, I had no choice but to use the pfam_scan.pl script locally to get the output file in the right format. But it worked!

**Comment by chunxubioinfor** [comment]
I'm closing this issue. If you require any further assistance, please don't hesitate to let me know.
