### ISSUE TITLE
import data directly from TCGA

### ISSUE THREAD

**Issue by zhumengyan** [kvittingseerup/IsoformSwitchAnalyzeR#32]

**Comment by zhumengyan** [comment]
Thanks for the great tools for scientific community!
I have a questions. Can I import TCGA isoform data downloaded from firehose?

**Comment by kvittingseerup** [comment]
You can use IsoformSwitchAnalyzeR with any full length transcript quantification so in principle yes. In practice it is a bit harder because TCGA have used the UCSC knowngenes annotation to quantify the data and that is not well suited for switch analysis mainly due to the lack of gene_id annotation. You can read more about it in the [google group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!searchin/isoformswitchanalyzer/tcga%7Csort:date/isoformswitchanalyzer/GLWXay40bVA/NkGEYY6wFQAJ).
You can also see how I solved the problem for [our paper ](http://mcr.aacrjournals.org/content/15/9/1206.long) about isoforms switches in the TCGA data. Lastly there is a lot of supplementary materials - e.g. the switchAnalyzeRLists of the [TCGA data](doi.org/10.6084/m9.figshare.4924724) etc.
