### ISSUE TITLE
Question: calculation of dIF

### ISSUE THREAD

**Issue by fifdick** [kvittingseerup/IsoformSwitchAnalyzeR#37]
Hi, 
I have a question concerning the calculation of dIF , which is done internally to (I guess) filter isoforms by user given dIFCutoff.
How do you calculate dIF, i.e. how do you calculate a conditions isoform fraction for one isoform?
Going through you code I got the idea (I might be wrong) that you calculate these values form the isoform fractions that are: the normalized count value of isoform A divided by the sum of isoform A count and isoform B count (assuming the gene has only left isoform A and B after filtering). Do you then simply take the mean isoform fraction of a condition of a isoform of intrest as the value IF for one condition? Hence dIF would be abs(IF_cond1 - IF_cond2)?
Is that correct? Would there be reasoning for being interested in a dIF value that is based on fitted count values rather than the observed ones? Is there no function available in DRIMSeq that provides the dIF ? And furthermore, is the dIF from IsoformswitchanalyzeR in any way compareable to DEXSeq's function estimateExonFoldChange (if applied to transcript counts of course?). Im trying to get a better understanding as to what exactly dIF describes. Thanks in adavnce.

**Comment by kvittingseerup** [comment]
IF values are calculated as: <iso_exp> / <parent_gene_exp> using normalised abundance values. This is mainly done to take into account the differences in isoform lengths which skews raw read counts.

dIF values are just IF2 - IF1 (so a positive value indicate the isoform is used more).

For an example of these please check figure 1 of [this article](http://mcr.aacrjournals.org/content/15/9/1206).

IF and dIF are very nice measures as they directly relate to isoform usage and thereby can be interpreted in terms of the output from a specific gene. That is why IsoformSwitchAnalyzeR uses IF/dIF instead of log2FC.

And unfortunately there is currently no equivalent measure of the effect size in neither DRIMSeq or DEXSeq in terms of IF/dIF.
