### ISSUE TITLE
change edgeR normalization to DESeq2 method

### ISSUE THREAD

**Issue by JamalEH** [kvittingseerup/IsoformSwitchAnalyzeR#51]
Hi,
I have two questions:
1. Since I performed my DE analysis of genes and isoforms using Salmon-tximport-DESeq2 pipelines, is it possible to modify the scripts of importIsoformExpression() functions to allow DESeq2 normalization method of TMP units instead of the used edgeR method (TMM as the default option)?
If so, how can I do that when modifying the script?
Otherwise, if you think, according to your expertise, that using edgeR normalization method is fine or if I should re-run DE analysis using edgeR, I would be very thankful if you can help me with this.

2. Is it also possible to use the normalized read counts instead of the TPM units to analyse isoform switching? I main by normalized counts (counts were normalized for both library size differences and for average transcript lengths using tximport). I also set calculateCountsFromAbundance argument to TRUE when importing Salmon data in switchAnalyzeR.

Thank you so much in advance for your help!
Best regards,
Jamal.

**Comment by kvittingseerup** [comment]
Hi Jamal

Thanks for reaching out.

I will answer in opposite order

Answer 2: IsoformSwitchAnalyzeR requires count data for the statistical analysis - it only uses the TPM values to estimate the isoform fraction (since they are normalized for read-length etc).

Answer 1:  The default DESeq2 normalization method and the edgeR TMM method is quite similar - but if you want to modify my scripts you can naturally do it (but unfortunately I cannot offer help in that regard - you will have to figure it out yourself). But importantly the normalisation is only used on the TPM values - not the count values.  This is important because as mentioned above IsoformSwitchAnalyzeR uses the count data for the statistical analysis. It does this by wrapping DEXSeq - which itself relies on DESeq2 - meaning that if you pair the IsoformSwitchAnalyzeR analysis with a DESeq2 analysis it is the same normalization that have been done - and it is the combination I would suggest.
