### ISSUE TITLE
switchPlot questions

### ISSUE THREAD

**Issue by rmurray2** [kvittingseerup/IsoformSwitchAnalyzeR#58]
This is a great package, thanks for developing it!

![hgf_switch](https://user-images.githubusercontent.com/5521035/74524100-0d14b080-4f27-11ea-9af0-022d8bb54153.png)
![hgf_uniprot](https://user-images.githubusercontent.com/5521035/74524109-100fa100-4f27-11ea-9661-b925a6fd86aa.png)

1) Is "ENSMUST00000195957.4" not labeled with domain information because there is disagreement between the GTF file and CPC2 predictions as to whether it is coding? Is there a way to override this?

2) Is it fair to assume that the unlabeled domains for ENSMUST00000195957.4 that align exactly with labeled domains from other transcripts can be labeled in the same way? 

3) Isoforms of this protein are known to have up to four Kringle domains, (the number varies depending on the isoform; see uniprot screenshot). Looking at the switchPlot, I see eight domains labeled as "Kringle". Is it possible to find out how these eight labeled domains combine to form the four known ones? Would it be possible to add a label of some kind to show how the labeled domains in the plot relate to AA locations? 

4) Why is there a "x4" in the Kringle domain legend? Where is that information coming from?

**Comment by kvittingseerup** [comment]
Hi 

Thanks for reaching out. 

1) The most likely explanation is that there is no open reading frame annotated for ENSMUST00000195957.4. And yes it is in the "coding" part of the plot because of the CPC2 analysis. Do you mean predicting ORF from ENSMUST00000195957.4 or removing the CPC2 annotation?
2) Sort answer: no. Long answer: If you are 100% sure the overlapping exons occupy the same genomic positions then most likely (but not definitely). But you cannot state this from a plot (small changes will not be visible). Anyways I would recommend doing the analysis instead. 
3) I can only see 4 Kringle domains (but each spans two exons - is that what you mean?)
4) That is just a way of saying there are 4 of them and assigning them all the same color (instead of each getting their own color). You can control this behaviour via the arguments passed on to the switchPlotTranscript function.

Also note the region sizes in the switchPlot are scaled so are not comparable. See the "rescaleTranscripts" argument.

**Comment by rmurray2** [comment]
Thanks so much for your prompt reply!

> Do you mean predicting ORF from ENSMUST00000195957.4 or removing the CPC2 annotation?

I mean predicting the ORF for ENSMUST00000195957.4. Ideally, I'd like to also see domain information for that transcript, especially since it is predicted to be coding.

**Comment by kvittingseerup** [comment]
There is not an easy way to do this for only a specific isoform - which would also be unfair to all other transcripts (both in this and other genes). 

You can take a step back and use the analyzeORF() function to de-novo predict ORFs for all transcripts (this is very accurate and can even be refined by the CPC2 data). But this would mean that all analysis of predicted protein (e.g. pfam) would need to be re-run along with all downstream analysis done by IsoformSwitchAnalyzeR.
