### ISSUE TITLE
Error of IsoformSwitchAnalyzeR

### ISSUE THREAD

**Issue by Kai4010** [kvittingseerup/IsoformSwitchAnalyzeR#6]
I would like to use IsoformSwitchAnalyzeR.

I used the data that I got from cuffdiff(ver.2.2.1).
when I used importCufflinksFiles function to import data of cuffdiff directly, this error appeared.

  Error in `$<-.data.frame`(`*tmp*`, "isoform_switch_q_value", value = NA) : 
  replacement has 1 row, data has 0

How can I avoid this error?

**Comment by kvittingseerup** [comment]
Could you provide the code you used?

**Comment by Kai4010** [comment]
testSwitchList <- importCufflinksFiles(
    pathToGTF                      = "genes.gtf",
    pathToGeneDEanalysis           = "gene_exp.diff",
    pathToIsoformDEanalysis        = "isoform_exp.diff",        
    pathToGeneFPKMtracking         = "genes.fpkm_tracking",        
    pathToIsoformFPKMtracking      = "isoforms.fpkm_tracking",      
    pathToIsoformReadGroupTracking = "isoforms.read_group_tracking",
    pathToSplicingAnalysis         = "splicing.diff",         
    pathToReadGroups               = "read_groups.info",             
    pathToRunInfo                  = "run.info",      
    fixCufflinksAnnotationProblem=TRUE,
    quiet=TRUE
)
testSwitchList

**Comment by kvittingseerup** [comment]
I cannot reproduce your problem. 

Can you run the command on the example data included in the package? (see code example at the bottom of the documentation page for importCufflinksFiles() ).

The error you are getting most likely occurs because of a problem with the files. Could you post the file sizes of each of the files you link to in the importCufflinksFiles() arguments.

**Comment by Kai4010** [comment]
I could run the command on the example data.

Below are the file sizes.
We are not sure whether they are too large for the analysis with the IsoformSwitchAnalyzeR.


yosuke@yosuke-virtual-machine[test] ll                              [11:48AM]
sum 226020
-rwxrw-rw- 1 yosuke yosuke       53  5月 29  2017 bias_params.info
-rwxrw-rw- 1 yosuke yosuke  1888046  5月 29  2017 cds.count_tracking
-rwxrw-rw- 1 yosuke yosuke  5578920  5月 29  2017 cds.diff
-rwxrw-rw- 1 yosuke yosuke  3302821  5月 29  2017 cds.fpkm_tracking
-rwxrw-rw- 1 yosuke yosuke 10039065  5月 29  2017 cds.read_group_tracking
-rwxrw-rw- 1 yosuke yosuke  8151366  5月 29  2017 cds_exp.diff
-rwxrw-rw- 1 yosuke yosuke  7908133  5月 29  2017 gene_exp.diff
-rwxrw-rw- 1 yosuke yosuke  1827527  5月 29  2017 genes.count_tracking
-rwxrw-rw- 1 yosuke yosuke  3183949  5月 29  2017 genes.fpkm_tracking
-rwxrw-rw- 1 yosuke yosuke 94926257  7月 22  2015 genes.gtf
-rwxrw-rw- 1 yosuke yosuke  9841727  5月 29  2017 genes.read_group_tracking
-rwxrw-rw- 1 yosuke yosuke 13455676  5月 29  2017 isoform_exp.diff
-rwxrw-rw- 1 yosuke yosuke  3168110  5月 29  2017 isoforms.count_tracking
-rwxrw-rw- 1 yosuke yosuke  5887187  5月 29  2017 isoforms.fpkm_tracking
-rwxrw-rw- 1 yosuke yosuke 18367873  5月 29  2017 isoforms.read_group_tracking
-rwxrw-rw- 1 yosuke yosuke  6777625  5月 29  2017 promoters.diff
-rwxrw-rw- 1 yosuke yosuke      764  5月 29  2017 read_groups.info
-rwxrw-rw- 1 yosuke yosuke      462  5月 29  2017 run.info
-rwxrw-rw- 1 yosuke yosuke  7570249  5月 29  2017 splicing.diff
-rwxrw-rw- 1 yosuke yosuke  8885298  5月 29  2017 tss_group_exp.diff
-rwxrw-rw- 1 yosuke yosuke  2050562  5月 29  2017 tss_groups.count_tracking
-rwxrw-rw- 1 yosuke yosuke  3553116  5月 29  2017 tss_groups.fpkm_tracking
-rwxrw-rw- 1 yosuke yosuke 10879341  5月 29  2017 tss_groups.read_group_tracking
-rwxrw-rw- 1 yosuke yosuke  4137256  5月 29  2017 var_model.info

**Comment by kvittingseerup** [comment]
They are not to large - I've analyzed much larger datasets.

Where does genes.gtf originate from?

**Comment by Kai4010** [comment]
I took genes.gtf from UCSC(mm10).

**Comment by kvittingseerup** [comment]
And those are also the isoforms you quantified with cufflinks?

**Comment by Kai4010** [comment]
I used genes.gtf that was just downloaded from UCSC. I didn't make it with cufflinks.
Should I use gtf file that I got with cufflinks?

**Comment by kvittingseerup** [comment]
It should be the same file as you instructed CuffDiff to quantify (the file you passed to the -g/-G argument) - is it that?

**Comment by Kai4010** [comment]
I used different gtf file. It occured the error.
But, 
I changed cuffdiff data that was quantified with genes.gtf. Then, I got another error message. This is error message.

	Error in importCufflinksFiles(pathToGTF = "genes.gtf", pathToGeneDEanalysis = "gene_exp.diff",  : 
	The file supplied to pathToGeneDEanalysis does not appear to be the result of the CuffDiff gene expression analysis.

This is run.info of cuffdiff data.

cmd_line	cuffdiff -p 3 -o cuffdiff/Heart_group1,2,3_mm10annotation -L Group1,Group2,Group3 		GenomeSequence/mm10/Annotation/Genes/genes.gtf CM1/accepted_hits.bam,CM2/accepted_hits.bam,CM3/accepted_hits.bam CM4/accepted_hits.bam,CM5/accepted_hits.bam,CM6/accepted_hits.bam CM7/accepted_hits.bam,CM8/accepted_hits.bam,CM9/accepted_hits.bam 

In this case, I used same file(genes.gtf) between cuffdiff and IsoformSwitchAnaryzeR.

Why the error occured?

**Comment by kvittingseerup** [comment]
I think that is a problem with my code (one of the sanity checks i make on the files supplied are the right once) - but to be sure could you paste the head of the "gene_exp.diff" file?

**Comment by Kai4010** [comment]
Below are "gene_exp.diff".

test_id	gene_id	gene	locus	sample_1	sample_2	status	value_1	value_2	log2(fold_change)	test_stat	p_value	q_value	significant
0610005C13Rik	0610005C13Rik	0610005C13Rik	chr7:45567794-45589710	Group1	Group2	NOTEST	0.499429	0	-inf	0	1	1	no
0610007P14Rik	0610007P14Rik	0610007P14Rik	chr12:85815454-85824545	Group1	Group2	OK	19.5296	15.9181	-0.29499	-0.429797	0.44005	0.56272	no

**Comment by kvittingseerup** [comment]
My suspicions were correct - but I will unfortunately not have time to make the updates before next week. 

I had not foreseen that people would youse CuffDiff to quantify known annotation since there are much better pipelines for that. If you want to quantify known annotation I would recommend either of:
- [Salmon](https://github.com/COMBINE-lab/salmon) / [DESeq2](https://bioconductor.org/packages/release/bioc/html/DESeq2.html) pipeline - see [here](https://bioconductor.org/packages/3.7/bioc/vignettes/DESeq2/inst/doc/DESeq2.html)
- [Kallisto](https://github.com/pachterlab/kallisto) / [Sleuth](https://github.com/pachterlab/sleuth) pipeline

Which are both state-of-the art and both are directly supported by IsoformSwitchAnalyzeR via the importIsoformExpression() function.


The cufflinks/cuffdiff pipeline is only appropriate if you want to identify novel transcripts from the RNA-seq data where you would supply the output from cuffmerge to cuffdiff - see more [here](http://cole-trapnell-lab.github.io/cufflinks/getting_started/#common-uses-of-the-cufflinks-package)

**Comment by kvittingseerup** [comment]
The promised update is now up.
