### ISSUE TITLE
if I have one condition e.g only have cancer samples without normal

### ISSUE THREAD

**Issue by linfanxiao** [kvittingseerup/IsoformSwitchAnalyzeR#60]
This is a great package, thanks for optimizing it!

And there are two questions bother me.Could you give me some favor? PLZ

1. I wanna analyze RNA-seq data-set including 113 patient's samples. However ,there is no paired normal samples .So  I can analyze this data-set alone or  with another data-set which has  normal sample?
2. what is the difference between DIF and PSI? I know the mean of IF is  isoform_exp / gene_exp and PSI is  splice_in / (splice_in +splice_out. 

Thanks for your time !

**Comment by kvittingseerup** [comment]
For question 1:
You need data with at lest 2 conditions (sick vs healthy, treated vs untreated, etc). If the data does not contain normal samples it will be tricky to analyze as you cannot just take another RNAseq dataset of normal samples due to batch effects.

For question 2:
IF and PSI are equivalent in that they both quantify the relative usage. The difference is that PSI measure the usage of a splice-site or splice event whereas IF measures the isoform usage. 

Likewise dIF and deltaPSI (dPSI) are equivivalent in that they quantify the difference between two conditions.

Hope this helps

Cheers
Kristoffer
