### ISSUE TITLE
analyzePFAM error

### ISSUE THREAD

**Issue by ashokpatowary** [kvittingseerup/IsoformSwitchAnalyzeR#63]
Hi @kvittingseerup 

I am trying to run analyzePFAM on my data and hitting the following error.
<img width="542" alt="Screen Shot 2020-04-25 at 12 39 05 AM" src="https://user-images.githubusercontent.com/42618005/80274244-df1dbc00-868d-11ea-82b4-8eb1b5277c18.png">

I am using version 1.9.5

pfam file was generated by:

`pfam_scan.pl -fasta isoformSwitchAnalyzeR_isoform_AA.fasta -dir PfamDB/ -outfile pfam_AA`

pfam file output

<img width="1331" alt="Screen Shot 2020-04-25 at 12 51 43 AM" src="https://user-images.githubusercontent.com/42618005/80274413-ff9a4600-868e-11ea-9b9e-0837162f4d17.png">

**Comment by kvittingseerup** [comment]
Thanks for reaching out - all your data looks correct so the error seems strange.

For me to debug this I would need (a subset of) the result file (which results in the error).

Cheers
Kristoffer

**Comment by ashokpatowary** [comment]
@kvittingseerup 

Did you get a chance to look at the results file I had send you? If you need any further information please do let me know.

Thanks

**Comment by kvittingseerup** [comment]
Hi @ashokpatowary 

Sorry for the slow response - I'm on parental leave so have very little time to work :-)

I did manage to look at the file you send me and the problem is the importing of the fixed width format file outputted by the pfam_scan.pl as I have to guess the width of each file individually - for some reason this goes wrong with your file.

Could you send me a larger chunk of the file (preferably 500+ lines) so I have more data to work with to try and figure it out?

Cheers
Kristoffer

**Comment by kvittingseerup** [comment]
Hi @ashokpatowary 

I think I found the problem. Turns out the `pfam_scan.pl` does not produce the fixed width file correctly when they type is "Coiled-coil" as seen from this part of the file:

```
iso1       7    101      6    101 PF04732.14  Filament_head     Family     2    87    87     74.3   1.1e-20   1 No_clan  
iso2     102    410    102    410 PF00038.21  Filament         Coiled-coil     1   312   312    381.9  2.7e-114   1 No_clan  
iso3      79    154     52    155 PF01399.27  PCI               Domain    29   103   105     24.7   2.5e-05   1 CL0123   
```

I've updated IsoformSwitchAnalyzeR to handle it - could you try if it works by updating from the github via this command:

```
if (!requireNamespace("devtools", quietly = TRUE)){
    install.packages("devtools")
}
devtools::install_github("kvittingseerup/IsoformSwitchAnalyzeR", build_vignettes = TRUE)
```

Cheers
Kristoffer

**Comment by ashokpatowary** [comment]
Hi @kvittingseerup 

With the updates analyzePFAM is working perfect.

Thanks
