### ISSUE TITLE
Question about inferential replicates from input quantification files

### ISSUE THREAD

**Issue by shnmunk** [kvittingseerup/IsoformSwitchAnalyzeR#88]
Dear @kvittingseerup,

Does IsoformSwitchAnalyzeR import/make use of inferential replicates if present in e.g. Salmon quant files?

Thanks in advance,
Sebastian

**Comment by kvittingseerup** [comment]
Unfortunately not. Also for the DTU analysis I have not seen people showing what is the optimal way of doing it (and that it is actually better than not using them). The exception to this is naturally BANDITS - but that is to slow to run without a large server anyways which is why it is not supported by IsoformSwitchAnalyzeR.

If you have any ideas or references feel free to share them  - then they could end up in a future version of IsoformSwitchAnalyzeR

Cheers
Kristoffer

**Comment by shnmunk** [comment]
Thanks for the clarification and the quick response.
I will keep that in mind for the future and post it here.

Cheers,
Sebastian
